"""
accounts/forms.py
=================
Django forms for the accounts app (login, registration, profile editing).
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User, UserProfile


class LoginForm(forms.Form):
    """Simple username / password login form."""

    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Username',
            'autofocus': True,
        }),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Password',
        }),
    )


class UserRegistrationForm(UserCreationForm):
    """Admin-only form to create a new user with a role assignment."""

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'role', 'department']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'role': forms.Select(attrs={'class': 'form-select'}),
            'department': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Style the password fields generated by UserCreationForm
        for field_name in ('password1', 'password2'):
            self.fields[field_name].widget.attrs['class'] = 'form-control'


class UserProfileForm(forms.ModelForm):
    """Form for users to edit their own profile details."""

    class Meta:
        model = UserProfile
        fields = ['bio', 'email_notifications']
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'email_notifications': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }
