# Generated by Django 4.2.30 on 2026-05-24 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatIntelFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('IOC', 'Indicator of Compromise'), ('TTP', 'Tactics, Techniques & Procedures'), ('ADVISORY', 'Security Advisory'), ('ACTOR', 'Threat Actor Profile')], max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('relevance_score', models.PositiveSmallIntegerField(default=0)),
                ('is_actioned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_threat_intel_feed',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'Remediation In Progress'), ('MITIGATED', 'Mitigated'), ('ACCEPTED', 'Risk Accepted'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('discovered_at', models.DateField(blank=True, null=True)),
                ('remediation_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_systems', models.ManyToManyField(blank=True, related_name='vulnerabilities', to='monitoring.healthcaresystem')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vulnerabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vulnerability',
                'verbose_name_plural': 'Vulnerabilities',
                'db_table': 'risk_vulnerability',
                'ordering': ['-cvss_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low (0–3.9)'), ('MEDIUM', 'Medium (4.0–6.9)'), ('HIGH', 'High (7.0–8.9)'), ('CRITICAL', 'Critical (9.0–10)')], max_length=10)),
                ('threat_likelihood', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('impact_magnitude', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('vulnerability_index', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('control_effectiveness', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('rationale', models.TextField(blank=True)),
                ('calculation_inputs', models.JSONField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computed_risk_scores', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='monitoring.healthcaresystem')),
            ],
            options={
                'db_table': 'risk_score',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['system', '-computed_at'], name='risk_score_system__683540_idx')],
            },
        ),
    ]
