# Generated by Django 4.2.30 on 2026-05-24 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceframework',
            name='applicable_region',
            field=models.CharField(blank=True, default='Global', max_length=100),
        ),
        migrations.AddField(
            model_name='complianceframework',
            name='framework_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('overall_score', models.FloatField(default=0.0)),
                ('compliance_level', models.CharField(choices=[('NON_COMPLIANT', 'Non-Compliant (<40%)'), ('PARTIAL', 'Partially Compliant (40–69%)'), ('COMPLIANT', 'Compliant (70–89%)'), ('FULLY_COMPLIANT', 'Fully Compliant (≥90%)')], default='NON_COMPLIANT', max_length=20)),
                ('total_controls', models.IntegerField(default=0)),
                ('passed_controls', models.IntegerField(default=0)),
                ('failed_controls', models.IntegerField(default=0)),
                ('summary_json', models.JSONField(default=dict)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='compliance_reports/')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='compliance.complianceframework')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_report',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('control_code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('control_category', models.CharField(choices=[('ACCESS_CONTROL', 'Access Control'), ('AUDIT_LOGGING', 'Audit Logging'), ('ENCRYPTION', 'Encryption'), ('INCIDENT_RESPONSE', 'Incident Response'), ('RISK_MANAGEMENT', 'Risk Management'), ('PHYSICAL_SECURITY', 'Physical Security'), ('TRAINING', 'Training & Awareness'), ('DATA_BACKUP', 'Data Backup'), ('PASSWORD_POLICY', 'Password Policy'), ('NETWORK_SECURITY', 'Network Security')], default='ACCESS_CONTROL', max_length=25)),
                ('weight', models.FloatField(default=1.0, help_text='Importance weight for scoring (0.0–1.0).')),
                ('automated_check', models.BooleanField(default=False, help_text='Whether the system can verify this control automatically.')),
                ('check_function_name', models.CharField(blank=True, help_text='Name of the ComplianceChecker method to call.', max_length=80)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_controls', to='compliance.complianceframework')),
            ],
            options={
                'db_table': 'compliance_engine_control',
                'ordering': ['framework', 'control_code'],
                'unique_together': {('framework', 'control_code')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PARTIAL', 'Partial'), ('NOT_APPLICABLE', 'Not Applicable'), ('PENDING', 'Pending Manual Review')], default='PENDING', max_length=20)),
                ('score', models.FloatField(default=0.0, help_text='0–100 score for this control.')),
                ('notes', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True, help_text='What was observed/checked.')),
                ('remediation_steps', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, help_text='Remediation deadline.', null=True)),
                ('checked_by', models.ForeignKey(blank=True, help_text='Null when the check was automated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checks', to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compliance.compliancecontrol')),
            ],
            options={
                'db_table': 'compliance_check_result',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['control', '-checked_at'], name='compliance__control_22c9c1_idx'), models.Index(fields=['status', '-checked_at'], name='compliance__status_4a43d5_idx')],
            },
        ),
    ]
