# Generated by Django 4.2.30 on 2026-05-24 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('RISK', 'Risk Summary Report'), ('COMPLIANCE', 'Compliance Status Report'), ('INCIDENT', 'Incident Report'), ('AUDIT', 'Audit Log Export'), ('VULN', 'Vulnerability Report'), ('EXEC', 'Executive Summary')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_generated_report',
                'ordering': ['-generated_at'],
            },
        ),
    ]
