"""
monitoring/management/commands/generate_sample_data.py
=======================================================
Management command to populate the database with realistic sample data for
demo and testing purposes.

Creates:
  - 100 simulated patient records spread across several departments
  - 500 access log entries with varied access types and times
  - Intentionally suspicious entries:
      * 20 after-hours access events (access_hour < 7 or > 20)
      *  5 bulk download events (>10 records accessed within 1 hour)
      * 10 cross-department access events
      *  3 critical record unauthorized attempts

Usage::

    python manage.py generate_sample_data
    python manage.py generate_sample_data --clear  # wipe existing sample data first
"""

import random
import uuid
from datetime import timedelta

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.utils import timezone

from monitoring.engine import MonitoringEngine
from monitoring.models import (
    PatientRecord,
    RecordAccessLog,
    SuspiciousActivity,
)

User = get_user_model()
engine = MonitoringEngine()

DEPARTMENTS = [
    'Cardiology', 'Neurology', 'Oncology', 'Radiology',
    'Paediatrics', 'Emergency', 'ICU', 'Pharmacy',
    'Laboratory', 'Orthopaedics',
]

DEVICES = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X) Safari/17',
    'Mozilla/5.0 (X11; Linux x86_64) Firefox/121',
    'Mozilla/5.0 (iPad; CPU OS 17) AppleWebKit Mobile',
]

IPS = ['192.168.1.10', '192.168.1.22', '10.0.0.5', '10.0.0.18', '172.16.0.3']

RECORD_TYPES = [rt[0] for rt in PatientRecord.RecordType.choices]
SENSITIVITY_WEIGHTS = {
    'LOW': 35,
    'MEDIUM': 40,
    'HIGH': 20,
    'CRITICAL': 5,
}
ACCESS_TYPES = [at[0] for at in RecordAccessLog.AccessType.choices]


class Command(BaseCommand):
    """Populate the database with 100 patient records and 500 access logs."""

    help = 'Generate sample patient records and access logs for demo/testing.'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Delete all existing sample data before generating new data.',
        )

    def handle(self, *args, **options):
        if options['clear']:
            self.stdout.write('Clearing existing sample data…')
            SuspiciousActivity.objects.all().delete()
            RecordAccessLog.objects.all().delete()
            PatientRecord.objects.all().delete()
            self.stdout.write(self.style.WARNING('Existing data cleared.'))

        users = self._get_or_create_users()
        self.stdout.write(f'Using {len(users)} users.')

        records = self._create_patient_records(users)
        self.stdout.write(self.style.SUCCESS(f'Created {len(records)} patient records.'))

        self._create_access_logs(users, records)
        self.stdout.write(self.style.SUCCESS('Created 500 access log entries.'))

        suspicious_count = SuspiciousActivity.objects.count()
        self.stdout.write(
            self.style.SUCCESS(
                f'Done. {suspicious_count} suspicious activities auto-generated by engine.'
            )
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _get_or_create_users(self):
        """Return existing users or create lightweight demo accounts."""
        users = list(User.objects.filter(is_active=True)[:6])
        if len(users) < 3:
            demo_accounts = [
                dict(username='dr_okafor', first_name='Emeka', last_name='Okafor',
                     email='okafor@demo.hs', department='Cardiology',
                     role='ANALYST', password='DemoPass!2024'),
                dict(username='nurse_adaeze', first_name='Adaeze', last_name='Nwosu',
                     email='adaeze@demo.hs', department='Neurology',
                     role='VIEWER', password='DemoPass!2024'),
                dict(username='radiologist', first_name='Kemi', last_name='Adeyemi',
                     email='kemi@demo.hs', department='Radiology',
                     role='ANALYST', password='DemoPass!2024'),
                dict(username='it_admin', first_name='Tunde', last_name='Balogun',
                     email='tunde@demo.hs', department='ICT',
                     role='ADMIN', password='DemoPass!2024'),
                dict(username='pharmacist', first_name='Blessing', last_name='Eze',
                     email='blessing@demo.hs', department='Pharmacy',
                     role='VIEWER', password='DemoPass!2024'),
            ]
            for acc in demo_accounts:
                password = acc.pop('password')
                user, created = User.objects.get_or_create(
                    username=acc['username'], defaults={**acc, 'must_change_password': False}
                )
                if created:
                    user.set_password(password)
                    user.save()
                    self.stdout.write(f'  Created demo user: {user.username}')
                if user not in users:
                    users.append(user)

        return users

    def _create_patient_records(self, users):
        """Create 100 simulated patient records across departments."""
        sensitivity_pool = []
        for level, weight in SENSITIVITY_WEIGHTS.items():
            sensitivity_pool.extend([level] * weight)

        records = []
        for i in range(1, 101):
            record = PatientRecord.objects.create(
                patient_code=f'PAT-{i:05d}',
                record_type=random.choice(RECORD_TYPES),
                sensitivity_level=random.choice(sensitivity_pool),
                department=random.choice(DEPARTMENTS),
                created_by=random.choice(users),
            )
            records.append(record)
        return records

    def _create_access_logs(self, users, records):
        """
        Create 500 access log entries, including intentionally suspicious ones.

        Suspicious quota:
          - 20 after-hours access events
          - 5 bulk download events (>10 records in 1 simulated hour)
          - 10 cross-department access events
          - 3 critical record unauthorized attempts
        """
        now = timezone.now()
        created_logs = []

        # ── Normal access events (first 462 slots) ──
        for _ in range(462):
            user = random.choice(users)
            record = random.choice(records)
            days_back = random.randint(0, 29)
            # Normal business hours: 08:00–18:00
            hour = random.randint(8, 18)
            ts = (now - timedelta(days=days_back)).replace(hour=hour, minute=random.randint(0, 59), second=0)

            log = self._make_log(user, record, ts, hour, random.choice(DEVICES), random.choice(IPS))
            created_logs.append(log)

        # ── 20 after-hours access events ──
        for _ in range(20):
            user = random.choice(users)
            record = random.choice(records)
            days_back = random.randint(0, 14)
            hour = random.choice([0, 1, 2, 3, 4, 5, 21, 22, 23])
            ts = (now - timedelta(days=days_back)).replace(hour=hour, minute=random.randint(0, 59), second=0)

            log = self._make_log(user, record, ts, hour, random.choice(DEVICES), random.choice(IPS))
            created_logs.append(log)
            self._analyse_log(log)

        # ── 5 bulk download events (simulate >10 records in ~1 hour by a single user) ──
        for _ in range(5):
            bulk_user = random.choice(users)
            days_back = random.randint(0, 7)
            base_ts = (now - timedelta(days=days_back)).replace(hour=random.randint(9, 15), minute=0, second=0)

            bulk_records = random.sample(records, min(12, len(records)))
            bulk_logs = []
            for j, rec in enumerate(bulk_records):
                ts = base_ts + timedelta(minutes=j * 3)
                log = self._make_log(bulk_user, rec, ts, ts.hour, DEVICES[0], IPS[0])
                bulk_logs.append(log)

            # Analyse the last log in the burst — it will see >10 records in 1 hour
            if bulk_logs:
                self._analyse_log(bulk_logs[-1])

        # ── 10 cross-department access events ──
        cross_dept_users = [u for u in users if hasattr(u, 'department') and u.department]
        for _ in range(10):
            user = random.choice(cross_dept_users) if cross_dept_users else random.choice(users)
            user_dept = getattr(user, 'department', '')
            # Pick a record from a different department
            diff_dept_records = [r for r in records if r.department != user_dept]
            record = random.choice(diff_dept_records) if diff_dept_records else random.choice(records)
            days_back = random.randint(0, 14)
            hour = random.randint(9, 17)
            ts = (now - timedelta(days=days_back)).replace(hour=hour, minute=random.randint(0, 59), second=0)

            log = self._make_log(user, record, ts, hour, random.choice(DEVICES), random.choice(IPS))
            created_logs.append(log)
            self._analyse_log(log)

        # ── 3 critical record unauthorized attempts ──
        critical_records = [r for r in records if r.sensitivity_level == 'CRITICAL']
        if not critical_records:
            # Ensure at least 3 CRITICAL records exist for this scenario
            for i in range(3):
                rec = PatientRecord.objects.create(
                    patient_code=f'PAT-C{i:03d}',
                    record_type=random.choice(RECORD_TYPES),
                    sensitivity_level='CRITICAL',
                    department=random.choice(DEPARTMENTS),
                    created_by=random.choice(users),
                )
                critical_records.append(rec)
                records.append(rec)

        for i in range(3):
            user = random.choice(users)
            record = critical_records[i % len(critical_records)]
            hour = random.choice([0, 1, 2, 3, 22, 23])  # after-hours + critical
            days_back = random.randint(0, 7)
            ts = (now - timedelta(days=days_back)).replace(hour=hour, minute=random.randint(0, 59), second=0)
            unknown_device = f'UnknownBrowser/{random.randint(1,99)}'  # unseen device

            log = self._make_log(user, record, ts, hour, unknown_device, random.choice(IPS))
            created_logs.append(log)
            self._analyse_log(log)

    def _make_log(self, user, record, ts, hour, device, ip):
        """
        Create a RecordAccessLog entry with a backdated timestamp.

        Because RecordAccessLog.timestamp uses auto_now_add, we create
        the log first then update the timestamp via QuerySet.update()
        to bypass the immutability guard.
        """
        log = RecordAccessLog.objects.create(
            user=user,
            patient_record=record,
            access_type=random.choice(ACCESS_TYPES),
            ip_address=ip,
            device_info=device,
            access_hour=hour,
            session_key=uuid.uuid4().hex[:40],
        )
        # Backdate the timestamp
        RecordAccessLog.objects.filter(pk=log.pk).update(timestamp=ts)
        log.timestamp = ts
        return log

    def _analyse_log(self, log):
        """Run the MonitoringEngine on a log and persist suspicious findings."""
        try:
            score, flags = engine.analyze_access(log)
            engine.flag_suspicious_activity(log, score, flags)
        except Exception as exc:
            self.stderr.write(f'  Engine error for log {log.pk}: {exc}')
