# Generated by Django 4.2.30 on 2026-05-24 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('PASSWORD_CHANGE', 'Password Changed'), ('USER_CREATED', 'User Account Created'), ('USER_UPDATED', 'User Account Updated'), ('USER_DELETED', 'User Account Deleted'), ('ALERT_ACK', 'Alert Acknowledged'), ('ALERT_RESOLVED', 'Alert Resolved'), ('RISK_SCORE', 'Risk Score Computed'), ('REPORT_GEN', 'Report Generated'), ('DATA_EXPORT', 'Data Exported'), ('COMPLIANCE', 'Compliance Assessment Recorded'), ('SYS_ACCESS', 'System Accessed'), ('CONFIG', 'Configuration Changed'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('http_method', models.CharField(blank=True, max_length=10)),
                ('url_path', models.CharField(blank=True, max_length=500)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_log_timesta_8b04a8_idx'), models.Index(fields=['user', '-timestamp'], name='audit_log_user_id_79f582_idx'), models.Index(fields=['action', '-timestamp'], name='audit_log_action_cf8063_idx')],
            },
        ),
    ]
