# Generated by Django 4.2.30 on 2026-05-25 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogIntegrityCheck',
            fields=[
                ('check_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('total_logs_checked', models.PositiveIntegerField()),
                ('corrupted_logs', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(choices=[('INTACT', 'All Logs Intact'), ('TAMPERED', 'Tampering Detected'), ('ERROR', 'Check Error')], max_length=20)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'audit_integrity_check',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_log_action_cf8063_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='http_method',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='url_path',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_category',
            field=models.CharField(choices=[('AUTH', 'Authentication & Authorization'), ('DATA_ACCESS', 'Data Access'), ('DATA_MODIFICATION', 'Data Modification'), ('USER_MANAGEMENT', 'User Management'), ('COMPLIANCE', 'Compliance'), ('ALERT', 'Alert Management'), ('SYSTEM', 'System Events'), ('EXPORT', 'Data Export'), ('CONFIGURATION', 'Configuration Changes')], default='SYSTEM', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='checksum',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='log_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('ERROR', 'Error')], default='SUCCESS', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_model',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_category', '-timestamp'], name='audit_log_action__417a95_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['status', '-timestamp'], name='audit_log_status_6f0604_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='audit_log_target__775c76_idx'),
        ),
        migrations.AddField(
            model_name='auditlogintegritycheck',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlogintegritycheck',
            index=models.Index(fields=['-checked_at'], name='audit_integ_checked_a16a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogintegritycheck',
            index=models.Index(fields=['result'], name='audit_integ_result_238254_idx'),
        ),
    ]
