# Generated by Django 4.2.30 on 2026-05-24 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('alert_type', models.CharField(choices=[('SECURITY', 'Security'), ('COMPLIANCE', 'Compliance'), ('PERFORMANCE', 'Performance'), ('AVAILABILITY', 'Availability'), ('DATA_BREACH', 'Data Breach'), ('POLICY', 'Policy Violation')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACK', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('FP', 'False Positive')], default='NEW', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('affected_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.healthcaresystem')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.monitoringevent')),
            ],
            options={
                'db_table': 'alerts_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('phase', models.CharField(choices=[('PREP', 'Preparation'), ('DETECT', 'Detection & Analysis'), ('CONTAIN', 'Containment'), ('ERADICATE', 'Eradication'), ('RECOVER', 'Recovery'), ('POST', 'Post-Incident Activity'), ('CLOSED', 'Closed')], default='DETECT', max_length=20)),
                ('detected_at', models.DateTimeField()),
                ('contained_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('impact_assessment', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alerts', models.ManyToManyField(blank=True, related_name='incidents', to='alerts.alert')),
                ('incident_commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts_incident',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-created_at'], name='alerts_aler_status_e70a14_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', '-created_at'], name='alerts_aler_severit_f1bbe4_idx'),
        ),
    ]
