# Generated by Django 4.2.30 on 2026-05-25 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('THRESHOLD', 'Threshold-based'), ('PATTERN', 'Pattern-based'), ('RULE_ENGINE', 'Rule Engine'), ('MANUAL', 'Manual Review')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('SECURITY', 'Security Issue'), ('COMPLIANCE', 'Compliance Violation'), ('PERFORMANCE', 'Performance Degradation'), ('AVAILABILITY', 'Availability Issue'), ('DATA_BREACH', 'Data Breach Risk'), ('POLICY', 'Policy Violation'), ('UNAUTH_ACCESS', 'Unauthorized Access'), ('PRIV_ESCALATION', 'Privilege Escalation'), ('SUSPICIOUS', 'Suspicious Activity'), ('AUDIT_ANOMALY', 'Audit Anomaly')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('conditions', models.JSONField(default=dict, help_text='Rule conditions as JSON')),
                ('actions', models.JSONField(default=dict, help_text='Actions to take when rule matches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alerts_alert_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for filtering', max_length=500),
        ),
        migrations.AddField(
            model_name='incident',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_sequence',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='remediation_steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='timeline',
            field=models.JSONField(blank=True, default=list, help_text='Chronological event log'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('SECURITY', 'Security Issue'), ('COMPLIANCE', 'Compliance Violation'), ('PERFORMANCE', 'Performance Degradation'), ('AVAILABILITY', 'Availability Issue'), ('DATA_BREACH', 'Data Breach Risk'), ('POLICY', 'Policy Violation'), ('UNAUTH_ACCESS', 'Unauthorized Access'), ('PRIV_ESCALATION', 'Privilege Escalation'), ('SUSPICIOUS', 'Suspicious Activity'), ('AUDIT_ANOMALY', 'Audit Anomaly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_read', '-created_at'], name='alerts_aler_is_read_be931c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['assigned_to', 'status'], name='alerts_aler_assigne_28b530_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_number'], name='alerts_inci_inciden_15eff3_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['phase', '-detected_at'], name='alerts_inci_phase_56b484_idx'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['is_active', 'rule_type'], name='alerts_aler_is_acti_f3459c_idx'),
        ),
    ]
