# Generated by Django 4.2.30 on 2026-05-24 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('system_type', models.CharField(choices=[('EHR', 'Electronic Health Record'), ('LIS', 'Laboratory Information System'), ('PACS', 'Picture Archiving & Communication System'), ('HIS', 'Hospital Information System'), ('PHARMACY', 'Pharmacy System'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEGRADED', 'Degraded'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Under Maintenance')], default='ACTIVE', max_length=20)),
                ('contains_phi', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_systems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_healthcare_system',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classification', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('PHI', 'Protected Health Information'), ('PII', 'Personally Identifiable Information')], default='INTERNAL', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('record_count', models.PositiveBigIntegerField(default=0)),
                ('encrypted_at_rest', models.BooleanField(default=False)),
                ('encrypted_in_transit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_assets', to='monitoring.healthcaresystem')),
            ],
            options={
                'db_table': 'monitoring_data_asset',
            },
        ),
        migrations.CreateModel(
            name='MonitoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SECURITY', 'Security Incident'), ('PERFORMANCE', 'Performance Issue'), ('AVAILABILITY', 'Availability Issue'), ('COMPLIANCE', 'Compliance Violation'), ('CONFIG', 'Configuration Change'), ('DATA_ACCESS', 'Data Access Anomaly')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_events', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitoring.healthcaresystem')),
            ],
            options={
                'db_table': 'monitoring_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['-occurred_at'], name='monitoring__occurre_85a065_idx'), models.Index(fields=['severity', '-occurred_at'], name='monitoring__severit_cdac31_idx')],
            },
        ),
    ]
