# Generated by Django 4.2.30 on 2026-05-24 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('patient_code', models.CharField(db_index=True, max_length=20)),
                ('record_type', models.CharField(choices=[('MEDICAL_HISTORY', 'Medical History'), ('PRESCRIPTION', 'Prescription'), ('LAB_RESULT', 'Lab Result'), ('INSURANCE', 'Insurance'), ('IMAGING', 'Imaging'), ('PERSONAL_INFO', 'Personal Info')], max_length=20)),
                ('sensitivity_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_patient_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activity_type', models.CharField(choices=[('AFTER_HOURS', 'After-Hours Access'), ('BULK_DOWNLOAD', 'Bulk Download'), ('UNAUTHORIZED', 'Unauthorized Attempt'), ('PRIV_ESC', 'Privilege Escalation'), ('REPEATED_FAIL', 'Repeated Failed Access'), ('UNUSUAL_VOL', 'Unusual Volume'), ('CROSS_DEPT', 'Cross-Department Access')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('related_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_activities', to='monitoring.patientrecord')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_suspicious_activity',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['resolved', '-timestamp'], name='monitoring__resolve_90c906_idx'), models.Index(fields=['severity', '-timestamp'], name='monitoring__severit_1c732d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecordAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('access_type', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('DOWNLOAD', 'Download'), ('PRINT', 'Print'), ('DELETE', 'Delete'), ('SHARE', 'Share')], default='VIEW', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('access_hour', models.IntegerField(default=0)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False)),
                ('suspicion_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('patient_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='monitoring.patientrecord')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_record_access_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitoring__timesta_c4c09c_idx'), models.Index(fields=['user', '-timestamp'], name='monitoring__user_id_d98e1b_idx'), models.Index(fields=['is_suspicious', '-timestamp'], name='monitoring__is_susp_ff0f90_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='patientrecord',
            index=models.Index(fields=['sensitivity_level', '-created_at'], name='monitoring__sensiti_f190b6_idx'),
        ),
        migrations.AddIndex(
            model_name='patientrecord',
            index=models.Index(fields=['department'], name='monitoring__departm_b08863_idx'),
        ),
    ]
